import {
  LATEST_PERSISTED_STATE_VERSION,
  type Account,
  type Budget,
  type Category,
  type PersistedState,
  type RecurringRule,
  type Transaction,
} from "../types";

const SEED_TIMESTAMP = "2026-04-01T00:00:00.000Z";

export const seedAccounts: Account[] = [
  {
    id: "acct-checking",
    name: "checking",
    type: "checking",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "acct-savings",
    name: "savings",
    type: "savings",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "acct-credit",
    name: "credit card",
    type: "credit",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const seedCategories: Category[] = [
  {
    id: "cat-salary",
    name: "salary",
    kind: "income",
    color: "#16a34a",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "cat-rent",
    name: "rent",
    kind: "expense",
    color: "#dc2626",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "cat-groceries",
    name: "groceries",
    kind: "expense",
    color: "#2563eb",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "cat-dining",
    name: "dining",
    kind: "expense",
    color: "#f97316",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "cat-utilities",
    name: "utilities",
    kind: "expense",
    color: "#7c3aed",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "cat-fun",
    name: "fun",
    kind: "expense",
    color: "#db2777",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const seedRecurringRules: RecurringRule[] = [
  {
    id: "rule-rent",
    kind: "standard",
    name: "rent",
    amountCents: -180000,
    accountId: "acct-checking",
    categoryId: "cat-rent",
    merchant: "landlord",
    frequency: "monthly",
    startDate: "2026-04-01",
    active: true,
    dayOfMonth: 1,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "rule-paycheck",
    kind: "standard",
    name: "paycheck",
    amountCents: 250000,
    accountId: "acct-checking",
    categoryId: "cat-salary",
    merchant: "employer inc",
    frequency: "biweekly",
    startDate: "2026-04-03",
    active: true,
    dayOfWeek: 5,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "rule-streaming",
    kind: "standard",
    name: "streaming",
    amountCents: -1599,
    accountId: "acct-credit",
    categoryId: "cat-fun",
    merchant: "streamco",
    frequency: "monthly",
    startDate: "2026-04-12",
    active: true,
    dayOfMonth: 12,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "txn-rent-2026-04-01",
    kind: "standard",
    date: "2026-04-01",
    amountCents: -180000,
    accountId: "acct-checking",
    categoryId: "cat-rent",
    merchant: "landlord",
    source: "recurring",
    recurringRuleId: "rule-rent",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "txn-paycheck-2026-04-03",
    kind: "standard",
    date: "2026-04-03",
    amountCents: 250000,
    accountId: "acct-checking",
    categoryId: "cat-salary",
    merchant: "employer inc",
    source: "recurring",
    recurringRuleId: "rule-paycheck",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "txn-groceries-2026-04-05",
    kind: "standard",
    date: "2026-04-05",
    amountCents: -12450,
    accountId: "acct-checking",
    categoryId: "cat-groceries",
    merchant: "whole paycheck",
    note: "weekly groceries",
    source: "manual",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "txn-dining-2026-04-08",
    kind: "standard",
    date: "2026-04-08",
    amountCents: -4280,
    accountId: "acct-credit",
    categoryId: "cat-dining",
    merchant: "noodle place",
    source: "manual",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "txn-utilities-2026-04-10",
    kind: "standard",
    date: "2026-04-10",
    amountCents: -8750,
    accountId: "acct-checking",
    categoryId: "cat-utilities",
    merchant: "power company",
    source: "manual",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const seedBudgets: Budget[] = [
  {
    id: "budget-rent-2026-04",
    month: "2026-04",
    categoryId: "cat-rent",
    plannedCents: 180000,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "budget-groceries-2026-04",
    month: "2026-04",
    categoryId: "cat-groceries",
    plannedCents: 50000,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "budget-dining-2026-04",
    month: "2026-04",
    categoryId: "cat-dining",
    plannedCents: 20000,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "budget-utilities-2026-04",
    month: "2026-04",
    categoryId: "cat-utilities",
    plannedCents: 15000,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "budget-fun-2026-04",
    month: "2026-04",
    categoryId: "cat-fun",
    plannedCents: 10000,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const seedState: PersistedState = {
  version: LATEST_PERSISTED_STATE_VERSION,
  accounts: seedAccounts,
  categories: seedCategories,
  transactions: seedTransactions,
  budgets: seedBudgets,
  recurringRules: seedRecurringRules,
};

export function createSeedState(): PersistedState {
  return {
    version: LATEST_PERSISTED_STATE_VERSION,
    accounts: seedAccounts.map((item) => ({ ...item })),
    categories: seedCategories.map((item) => ({ ...item })),
    transactions: seedTransactions.map((item) => ({
      ...item,
      splits: item.splits?.map((split) => ({ ...split })),
    })),
    budgets: seedBudgets.map((item) => ({ ...item })),
    recurringRules: seedRecurringRules.map((item) => ({ ...item })),
  };
}