import type {
  account,
  budget,
  category,
  persistedstate,
  recurringrule,
  transaction,
} from "../types";

const timestamp = "2026-04-01T00:00:00.000Z";

export const seedaccounts: account[] = [
  {
    id: "acct-checking",
    name: "checking",
    type: "checking",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "acct-savings",
    name: "savings",
    type: "savings",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "acct-credit",
    name: "credit card",
    type: "credit",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const seedcategories: category[] = [
  {
    id: "cat-salary",
    name: "salary",
    kind: "income",
    color: "#16a34a",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "cat-rent",
    name: "rent",
    kind: "expense",
    color: "#dc2626",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "cat-groceries",
    name: "groceries",
    kind: "expense",
    color: "#2563eb",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "cat-dining",
    name: "dining",
    kind: "expense",
    color: "#f97316",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "cat-utilities",
    name: "utilities",
    kind: "expense",
    color: "#7c3aed",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "cat-fun",
    name: "fun",
    kind: "expense",
    color: "#db2777",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const seedrecurringrules: recurringrule[] = [
  {
    id: "rule-rent",
    name: "rent",
    amountCents: -180000,
    accountId: "acct-checking",
    categoryId: "cat-rent",
    merchant: "landlord",
    frequency: "monthly",
    startDate: "2026-04-01",
    active: true,
    dayOfMonth: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "rule-paycheck",
    name: "paycheck",
    amountCents: 250000,
    accountId: "acct-checking",
    categoryId: "cat-salary",
    merchant: "employer inc",
    frequency: "biweekly",
    startDate: "2026-04-03",
    active: true,
    dayOfWeek: 5,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "rule-streaming",
    name: "streaming",
    amountCents: -1599,
    accountId: "acct-credit",
    categoryId: "cat-fun",
    merchant: "streamco",
    frequency: "monthly",
    startDate: "2026-04-12",
    active: true,
    dayOfMonth: 12,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const seedtransactions: transaction[] = [
  {
    id: "txn-rent-2026-04-01",
    date: "2026-04-01",
    amountCents: -180000,
    accountId: "acct-checking",
    categoryId: "cat-rent",
    merchant: "landlord",
    source: "recurring",
    recurringRuleId: "rule-rent",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "txn-paycheck-2026-04-03",
    date: "2026-04-03",
    amountCents: 250000,
    accountId: "acct-checking",
    categoryId: "cat-salary",
    merchant: "employer inc",
    source: "recurring",
    recurringRuleId: "rule-paycheck",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "txn-groceries-2026-04-05",
    date: "2026-04-05",
    amountCents: -12450,
    accountId: "acct-checking",
    categoryId: "cat-groceries",
    merchant: "whole paycheck",
    note: "weekly groceries",
    source: "manual",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "txn-dining-2026-04-08",
    date: "2026-04-08",
    amountCents: -4280,
    accountId: "acct-credit",
    categoryId: "cat-dining",
    merchant: "noodle place",
    source: "manual",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "txn-utilities-2026-04-10",
    date: "2026-04-10",
    amountCents: -8750,
    accountId: "acct-checking",
    categoryId: "cat-utilities",
    merchant: "power company",
    source: "manual",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const seedbudgets: budget[] = [
  {
    id: "budget-rent-2026-04",
    month: "2026-04",
    categoryId: "cat-rent",
    plannedCents: 180000,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "budget-groceries-2026-04",
    month: "2026-04",
    categoryId: "cat-groceries",
    plannedCents: 50000,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "budget-dining-2026-04",
    month: "2026-04",
    categoryId: "cat-dining",
    plannedCents: 20000,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "budget-utilities-2026-04",
    month: "2026-04",
    categoryId: "cat-utilities",
    plannedCents: 15000,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "budget-fun-2026-04",
    month: "2026-04",
    categoryId: "cat-fun",
    plannedCents: 10000,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const seedstate: persistedstate = {
  version: 1,
  accounts: seedaccounts,
  categories: seedcategories,
  transactions: seedtransactions,
  budgets: seedbudgets,
  recurringRules: seedrecurringrules,
};

export function createseedstate(): persistedstate {
  return {
    version: 1,
    accounts: seedaccounts.map((item) => ({ ...item })),
    categories: seedcategories.map((item) => ({ ...item })),
    transactions: seedtransactions.map((item) => ({ ...item })),
    budgets: seedbudgets.map((item) => ({ ...item })),
    recurringRules: seedrecurringrules.map((item) => ({ ...item })),
  };
}